server:
  port: 8001
eureka:
  client:
    service-url:
      # eureka 服务地址
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: cloud-payment-provider8001
spring:
  application:
    # 设置应用的名称
    name: cloud-payment-provider
